stages:
  - build
  - sync

variables:
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$VERSION-$CI_PIPELINE_ID
  GROUP_ID: cn.com.xuxiaowei.ip
  ARTIFACT_ID: ip
  VERSION: 0.0.1-SNAPSHOT
  IP_JAVA_OPTS: -Xms256m -Xmx512m

build:
  stage: build
  image: maven:3.6.3-openjdk-17
  variables:
    MAVEN_OPTS: >-
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
    MAVEN_CLI_OPTS: >-
      --batch-mode
      --errors
      --fail-at-end
      --show-version
      --no-transfer-progress
      -DinstallAtEnd=true
      -DdeployAtEnd=true
  script:
    - free -h || cat /proc/meminfo
    - mvn -v
    - mvn clean compile jib:build -DskipTests=true -s settings.xml
    - free -h || cat /proc/meminfo
  cache:
    paths:
      - .m2/repository
  tags:
    - jihulab

build:deploy:
  stage: build
  needs:
    - job: build
  image: docker:cli
  variables:
    DOCKER_HOST: $DEPLOY_DOCKER_HOST
  script:
    - docker info
    - docker compose up -d
  environment: production
  tags:
    - g150s-docker

include:
  - /sync.yml
