server:
  port: ${IP_PORT:61450}
  forward-headers-strategy: NATIVE
  tomcat:
    # https://docs.spring.io/spring-boot/how-to/webserver.html#howto.webserver.use-behind-a-proxy-server.tomcat
    remoteip:
      # 从中提取远程IP的HTTP标头的名称。 例如，`X-Forwarded-For`、`X-Real-IP`。
      remote-ip-header: X-Forwarded-For
      # 用于覆盖原始端口值的HTTP标头的名称。
      port-header: X-Forwarded-Proto

spring:
  application:
    name: ip

ip:
  enable-asn: ${IP_ENABLE_ASN:false}
  asn-database: ${IP_ASN_DATABASE:}
  enable-city: ${IP_ENABLE_CITY:false}
  city-database: ${IP_CITY_DATABASE:}
