server:
  port: ${IP_PORT:61450}
  # forward-headers-strategy: NATIVE
  tomcat:
    # https://docs.spring.io/spring-boot/how-to/webserver.html#howto.webserver.use-behind-a-proxy-server.tomcat
    remoteip:
      # 从中提取远程IP的HTTP标头的名称。 例如，`X-FORWARDED-FOR`。
      remote-ip-header: X-Real-IP
      # 用于覆盖原始端口值的HTTP标头的名称。
      port-header: X-Forwarded-Proto

spring:
  application:
    name: ip
