server:
  port: ${IP_PORT:61450}
  forward-headers-strategy: NATIVE
  tomcat:
    # https://docs.spring.io/spring-boot/how-to/webserver.html#howto.webserver.use-behind-a-proxy-server.tomcat
    remoteip:
      # 从中提取远程IP的HTTP标头的名称。 例如，`X-Forwarded-For`、`X-Real-IP`。
      remote-ip-header: X-Forwarded-For
      # 用于覆盖原始端口值的HTTP标头的名称。
      port-header: X-Forwarded-Proto

spring:
  application:
    name: ip

logging:
  level:
    cn.com.xuxiaowei: debug
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{P-Request-Id} %clr(:){faint} %X{P-Remote-Host} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %X{P-Request-Id} : %X{P-Remote-Host} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    name: /logs/${spring.application.name}/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 365
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log.gz

ip:
  enable-asn: ${IP_ENABLE_ASN:false}
  asn-database: ${IP_ASN_DATABASE:}
  enable-city: ${IP_ENABLE_CITY:false}
  city-database: ${IP_CITY_DATABASE:}
  content-negotiation: ${IP_CONTENT_NEGOTIATION:false}
